blank_issues_enabled: false
contact_links:
  - name: SDK
    url: https://github.com/BelledonneCommunications/linphone-sdk
    about: Please post issues for SDK here.
  - name: Android
    url: https://github.com/BelledonneCommunications/linphone-android
    about: Please post issues for Android application here.
  - name: SDK
    url: https://github.com/BelledonneCommunications/linphone-iphone
    about: Please post issues for the iPhone application here.
  - name: SDK
    url: https://www.linphone.org/contact
    about: For any contacts like commercial, licensing, mailing-lists

